### ISSUE TITLE
전반적인 설정 전용 페이지 추가 필요

### ISSUE THREAD

**Issue by myyrakle** [tetrust/tetrust#38]
여러가지 핸들링 옵션이나 보이스 등 설정들을 모아서 보거나 바꿀 수 있는 페이지가 필요할듯함 
(tetrio처럼)

**Comment by ANDADAC** [comment]
[Handling]
ARR(Automatic Repeat Rate): DAS활성화됐을때 블록좌우이동속도(최대 5Frame, 최소 0Frame, 디폴트 2Frame)
DAS(Delayed Auto Shift): 좌우키를 누르고 자동반복이 활성화되기까지 걸리는 딜레이(최대 20F, 최소 1F, 디폴트 10F)
DCD(DAS cut delay: if not 0, any ongoing DAS movement will pause for a set amout of time after dropping/rotating a piece, measured in frames(20F, 0F, 0F)
SDF(Soft Drop Factor): Soft Drop 키를 눌렀을 때 중력속도를 몇 배 더 빠르게 하는지(5배 ~ 40배 또는 무한 즉시바닥)

[소리]
배경음악 크기 / 켜고 끄기 / 배경음악 고르기
효과음 크기 / 켜고 끄기

[컨트롤러]
키보드 맵핑 / 컨트롤러 맵핑 기능 추가
